/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classModel.Ant;
import classModel.Label1;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import static view.Game_View.labels;
import static view.Game_View.labelsLogic;

public class FinalView extends javax.swing.JFrame {

    int row = 0;
    int column = 0;
    int cube = 0;
    String name = "";
    int moves = 0;
    Border border = LineBorder.createBlackLineBorder();//Line border for labels

    public FinalView(int rows, int columns, int cubes, String nickname, int move) {
        initComponents();
        name = nickname;
        row = rows;
        column = columns;
        cube = cubes;
        moves = move;
        Labels();//Create labels
        text();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        move = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("MOVEMENTS:");

        move.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        move.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        move.setText("0");

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/game.png"))); // NOI18N
        jButton1.setText("New Game");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(move, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(move, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addContainerGap(312, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //This button is to open Game view
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Game_View view = new Game_View(row, column, cube, name);
        view.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        dispose();
        view.setLocationRelativeTo(null);
        view.setVisible(true);
        view.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    //This method is to created labels
    public void Labels() {
        int x = 0;
        int y = 0;
        int i = 0;
        int j = 0;
        for (int rows = 0; rows < row; rows++) {
            for (int columns = 0; columns < column; columns++) {
                labels[rows][columns] = new Label1(x, y, 40, 40);
                labels[rows][columns].setBorder(border);

                if (Game_View.logicF[rows][columns] == 10) {
                    labels[rows][columns].setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/gris.jpg")));
                }
                if (Game_View.logicF[rows][columns] == 3) {
                    labels[rows][columns].setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Azu.jpg")));
                }
                if (Game_View.logicF[rows][columns] == 4) {
                    labels[rows][columns].setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Alc.jpg")));
                }
                if (Game_View.logicF[rows][columns] == 5) {
                    labels[rows][columns].setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Poi.jpg")));
                }
                if (Game_View.logicF[rows][columns] == 8) {
                    labels[rows][columns].setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/PoiH.jpg")));
                }
                if (Game_View.logicF[rows][columns] == 6) {
                    labels[rows][columns].setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/AzuH.jpg")));
                }
                if (Game_View.logicF[rows][columns] == 7) {
                    labels[rows][columns].setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/AlcH.jpg")));
                }
                if (Game_View.logicF[rows][columns] == 0) {
                    labels[rows][columns].setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/fondoC.jpg")));
                }
                

                jPanel2.add(labels[rows][columns]);
                x += 40;//-

            }
            y += 40;// |
            x = 0;

        }

    }

    //This method is to set Text
    public void text() {
        move.setText(String.valueOf(moves));
        jPanel2.setFocusable(true);
        jPanel2.setOpaque(false);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalView(0, 0, 0, null, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel move;
    // End of variables declaration//GEN-END:variables
}
